version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mymarket-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: stockdb
      MYSQL_USER: marketuser
      MYSQL_PASSWORD: market123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 15

  api:
    image: yeteam/basicstockapp-api
    container_name: mymarket-api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=stockdb;User=marketuser;Password=market123"
      DOTNET_ENVIRONMENT: "Development"
    ports:
      - "8080:8080"

volumes:
  mysql_data:
